export const INC_COUNTER = 'INC_COUNTER';
export const INC_COUNTER_DELAYED = 'INC_COUNTER_DELAYED';

export const LOAD_STATIONS = 'LOAD_STATIONS';
export const LOAD_STATIONS_COMP = 'LOAD_STATIONS_COMP';
